### ISSUE TITLE
nalpha issue

### ISSUE THREAD

**Issue by DevonKerins** [Li-Reactive-Water-Group/HBV-BioRT#39]
When the nalpha value is set to anything other than zero the reaction rate for that reaction will equal zero for the whole timeseries. When nalpha = 0 there will be a reaction rate for the specified reaction.

This happens with my own input files as well as the Konza example file
[CoalCreek1.zip](https://github.com/Li-Reactive-Water-Group/HBV-BioRT/files/8524995/CoalCreek1.zip)
.

**Comment by KayalvizhiSadayappan** [comment]
I checked the water table depth in your input file. It always remains above 1500mm. The alpha value you have used is 0.9. For this alpha value, the reaction rate works out to be 0. That's why the output shows SOC reaction rate in UZ as 0. I tried alpha value of 0.002 and model outputs SOC reaction rate around E-7 in UZ (results file is attached here). I suggest calibrating alpha value.


[CoalCreek1_results_2204211152.txt](https://github.com/Li-Reactive-Water-Group/HBV-BioRT/files/8532543/CoalCreek1_results_2204211152.txt)

**Comment by DevonKerins** [comment]
Thanks for checking that. Is there some literature on a good range for this value?

Would it also be possible to change the example Konza file n_alpha value from 0.2? The example file doesn't run with this value and is a little misleading that the alpha value should be two orders of magnitude smaller.

**Comment by KayalvizhiSadayappan** [comment]
You can look at Wei's paper on Coal Creek. He has used alpha and also cited other relevant papers. While calibrating, you need to remember that depth and porosity you have used for the zone also influences the alpha value. So, you might have to consider them together. 

I will edit the Konza input file on GitHub. Thanks for bringing it up!
